# Go cross compiler (xgo): Go 1.10.x
# Copyright (c) 2018 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM aquachain/xgo-1.10.3

MAINTAINER Péter Szilágyi <peterke@gmail.com>
